#!/bin/bash

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=`readlink -f $0`
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=`dirname $SCRIPT`
echo "SCRIPTPATH: $SCRIPTPATH"

#create link for the tmux config file
rm ~/.tmux.conf
ln -s $SCRIPTPATH/tmux/tmux.conf ~/.tmux.conf
